"""Seed the AquaMax database with sample rehabilitation equipment catalog."""

from __future__ import annotations

import json
import sys
from pathlib import Path

# Add project root to path for imports
project_root = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(project_root))

from src.database.connection import init_database
from src.database.models import Product
from src.database.connection import get_session
from src.utils.logger import get_logger, setup_logging
from src.config.settings import settings

logger = get_logger(__name__)

SEED_PRODUCTS = [
    # Electrotherapy
    {
        "sku": "AM-ET-001",
        "name": "AquaMax TENS Unit Pro",
        "category": "Electrotherapy",
        "subcategory": "TENS",
        "description": "Professional-grade TENS unit with 24 modes for pain relief, muscle stimulation, and rehabilitation. Dual-channel output with rechargeable battery.",
        "price": 8499.0,
        "rating": 4.6,
        "stock": 45,
        "features": ["24 therapy modes", "Dual-channel", "Rechargeable Li-ion", "LCD display", "Timer function"],
        "specs": {"channels": 2, "modes": 24, "battery": "Li-ion 1800mAh", "weight": "280g"},
        "condition_tags": "chronic pain,back pain,muscle soreness,arthritis,post-surgery",
        "image_url": "https://example.com/images/tens-pro.jpg",
    },
    {
        "sku": "AM-ET-002",
        "name": "AquaMax EMS Muscle Stimulator",
        "category": "Electrotherapy",
        "subcategory": "EMS",
        "description": "Electrical muscle stimulation device for muscle strengthening, recovery, and rehabilitation. 20 intensity levels with 8 electrode pads.",
        "price": 6299.0,
        "rating": 4.4,
        "stock": 32,
        "features": ["20 intensity levels", "8 electrode pads included", "Muscle strengthening mode", "Recovery mode", "Portable design"],
        "specs": {"intensity_levels": 20, "pads": 8, "battery": "AAA x 4", "weight": "350g"},
        "condition_tags": "muscle atrophy,post-injury recovery,stroke rehabilitation,fitness training",
        "image_url": "https://example.com/images/ems-stim.jpg",
    },
    {
        "sku": "AM-ET-003",
        "name": "AquaMax Interferential Therapy Unit",
        "category": "Electrotherapy",
        "subcategory": "IFT",
        "description": "Clinical interferential therapy unit for deep tissue pain relief. 4-electrode configuration with sweep and vector modes.",
        "price": 24999.0,
        "rating": 4.7,
        "stock": 12,
        "features": ["4-electrode setup", "Sweep frequency", "Vector mode", "Deep tissue penetration", "Clinical grade"],
        "specs": {"frequency_range": "1-150 Hz", "output": "0-80mA", "channels": 4, "weight": "2.1kg"},
        "condition_tags": "deep tissue pain,sciatica,osteoarthritis,sports injury,chronic pain",
        "image_url": "https://example.com/images/ift-unit.jpg",
    },
    # Ultrasound Therapy
    {
        "sku": "AM-US-001",
        "name": "AquaMax Ultrasound Therapy System",
        "category": "Ultrasound Therapy",
        "subcategory": "Therapeutic Ultrasound",
        "description": "1 MHz and 3 MHz therapeutic ultrasound for tissue healing, pain reduction, and inflammation management. LCD touchscreen with preset protocols.",
        "price": 18500.0,
        "rating": 4.5,
        "stock": 18,
        "features": ["1 MHz & 3 MHz", "Touchscreen LCD", "Preset protocols", "Continuous & pulsed mode", "Treatment timer"],
        "specs": {"frequencies": "1, 3 MHz", "intensity": "0.5-3.0 W/cm²", "head_size": "5 cm²", "weight": "1.8kg"},
        "condition_tags": "tendonitis,sprains,soft tissue injury,inflammation,scar tissue",
        "image_url": "https://example.com/images/ultrasound.jpg",
    },
    {
        "sku": "AM-US-002",
        "name": "AquaMax Portable Ultrasound",
        "category": "Ultrasound Therapy",
        "subcategory": "Portable Ultrasound",
        "description": "Compact handheld ultrasound therapy device for home use and mobile physiotherapy. 1 MHz frequency with 3 intensity levels.",
        "price": 4999.0,
        "rating": 4.2,
        "stock": 60,
        "features": ["Handheld portable", "1 MHz frequency", "3 intensity levels", "Battery operated", "LED indicator"],
        "specs": {"frequency": "1 MHz", "intensity": "0.5-1.5 W/cm²", "battery": "Rechargeable", "weight": "150g"},
        "condition_tags": "home rehabilitation,mild pain,muscle spasms,minor injuries",
        "image_url": "https://example.com/images/ultrasound-portable.jpg",
    },
    # Exercise & Rehabilitation
    {
        "sku": "AM-EX-001",
        "name": "AquaMax Parallel Bars (Adjustable)",
        "category": "Exercise Equipment",
        "subcategory": "Gait Training",
        "description": "Heavy-duty adjustable parallel bars for gait training, balance exercises, and rehabilitation. Width and height adjustable with anti-slip platform.",
        "price": 32499.0,
        "rating": 4.8,
        "stock": 8,
        "features": ["Width: 50-70 cm adjustable", "Height: 75-100 cm adjustable", "Anti-slip platform", "500kg capacity", "Foldable"],
        "specs": {"material": "Steel", "length": "300cm", "max_weight": "500kg", "weight": "35kg"},
        "condition_tags": "stroke recovery, gait training, balance disorder, Parkinson's, post-surgery",
        "image_url": "https://example.com/images/parallel-bars.jpg",
    },
    {
        "sku": "AM-EX-002",
        "name": "AquaMax Multi-Gym Station",
        "category": "Exercise Equipment",
        "subcategory": "Multi-Gym",
        "description": "Comprehensive rehabilitation multi-gym for strength training, flexibility, and functional recovery. 8 stations with adjustable resistance.",
        "price": 84999.0,
        "rating": 4.9,
        "stock": 5,
        "features": ["8 exercise stations", "Adjustable resistance 5-100kg", "Physiotherapy protocols", "Safety locks", "Digital rep counter"],
        "specs": {"stations": 8, "resistance_range": "5-100kg", "footprint": "2.5m x 2m", "weight": "180kg"},
        "condition_tags": "strength training, ACL recovery, post-fracture, orthopedic rehab, sports injury",
        "image_url": "https://example.com/images/multi-gym.jpg",
    },
    {
        "sku": "AM-EX-003",
        "name": "AquaMax Resistance Band Set",
        "category": "Exercise Equipment",
        "subcategory": "Resistance Bands",
        "description": "Complete set of 5 resistance bands with handles, door anchor, and ankle straps. Ideal for progressive rehabilitation exercises.",
        "price": 1299.0,
        "rating": 4.3,
        "stock": 150,
        "features": ["5 resistance levels", "Handles included", "Door anchor", "Ankle straps", "Carrying bag"],
        "specs": {"resistance": "5-25kg", "length": "120cm", "material": "Latex", "weight": "400g"},
        "condition_tags": "home exercise, shoulder rehab, knee rehab, flexibility, general fitness",
        "image_url": "https://example.com/images/band-set.jpg",
    },
    {
        "sku": "AM-EX-004",
        "name": "AquaMax Balance Board Pro",
        "category": "Exercise Equipment",
        "subcategory": "Balance Training",
        "description": "Wobble balance board with adjustable difficulty for proprioception training, ankle rehabilitation, and core stability.",
        "price": 3499.0,
        "rating": 4.5,
        "stock": 42,
        "features": ["Adjustable tilt angle", "Non-slip surface", "360° rotation", "Max weight 150kg", "Progressive difficulty"],
        "specs": {"diameter": "40cm", "max_weight": "150kg", "material": "ABS + PVC", "weight": "1.2kg"},
        "condition_tags": "ankle sprain, balance training, proprioception, core stability, vestibular rehab",
        "image_url": "https://example.com/images/balance-board.jpg",
    },
    # Hydrotherapy
    {
        "sku": "AM-HT-001",
        "name": "AquaMax Underwater Treadmill",
        "category": "Hydrotherapy",
        "subcategory": "Aquatic Treadmill",
        "description": "Underwater treadmill for aquatic gait training, cardiovascular conditioning, and low-impact rehabilitation. Adjustable water depth and speed.",
        "price": 185000.0,
        "rating": 4.9,
        "stock": 3,
        "features": ["Speed: 0.5-8 km/h", "Adjustable depth", "Anti-corrosion frame", "Digital control panel", "Safety harness"],
        "specs": {"speed_range": "0.5-8 km/h", "depth": "adjustable", "motor": "2HP waterproof", "weight": "220kg"},
        "condition_tags": "aquatic therapy, gait training, arthritis, joint replacement, sports injury, low-impact cardio",
        "image_url": "https://example.com/images/underwater-treadmill.jpg",
    },
    {
        "sku": "AM-HT-002",
        "name": "AquaMax Hydrotherapy Pool System",
        "category": "Hydrotherapy",
        "subcategory": "Therapy Pool",
        "description": "Compact hydrotherapy pool with underwater massage jets, adjustable temperature, and modular installation for clinics and hospitals.",
        "price": 450000.0,
        "rating": 4.8,
        "stock": 2,
        "features": ["Underwater massage jets", "Temperature control 30-38°C", "Modular installation", "Filtration system", "Safety rails"],
        "specs": {"dimensions": "3m x 2m x 1.2m", "capacity": "7000L", "temperature": "30-38°C", "weight": "850kg"},
        "condition_tags": "chronic pain, fibromyalgia, cerebral palsy, spinal injury, neurological rehab",
        "image_url": "https://example.com/images/hydro-pool.jpg",
    },
    # Heat & Cold Therapy
    {
        "sku": "AM-HC-001",
        "name": "AquaMax Paraffin Wax Bath",
        "category": "Heat Therapy",
        "subcategory": "Paraffin Bath",
        "description": "Professional paraffin wax bath for heat therapy of hands, feet, and joints. Temperature-controlled with rapid melt and safety lock.",
        "price": 5499.0,
        "rating": 4.4,
        "stock": 28,
        "features": ["Temperature control 45-65°C", "Rapid melt technology", "Safety lock", "Capacity 3L", "Includes wax and liners"],
        "specs": {"capacity": "3L", "temperature": "45-65°C", "power": "300W", "weight": "2.5kg"},
        "condition_tags": "arthritis, joint stiffness, hand pain, carpal tunnel, Raynaud's",
        "image_url": "https://example.com/images/paraffin-bath.jpg",
    },
    {
        "sku": "AM-HC-002",
        "name": "AquaMax Cryotherapy Unit",
        "category": "Cold Therapy",
        "subcategory": "Cryotherapy",
        "description": "Localized cryotherapy unit for pain relief, inflammation reduction, and post-surgical recovery. Adjustable temperature and timer.",
        "price": 12999.0,
        "rating": 4.5,
        "stock": 15,
        "features": ["Temperature: -10°C to 15°C", "Adjustable timer", "Multiple applicators", "Digital display", "Portable"],
        "specs": {"temperature_range": "-10 to 15°C", "timer": "1-30 min", "applicators": 4, "weight": "4.2kg"},
        "condition_tags": "acute injury, post-surgical swelling, inflammation, sports injury, sprain",
        "image_url": "https://example.com/images/cryo-unit.jpg",
    },
    # Mobility Aids
    {
        "sku": "AM-MA-001",
        "name": "AquaMax Rollator Walker (Premium)",
        "category": "Mobility Aids",
        "subcategory": "Walker",
        "description": "Premium aluminum rollator with seat, backrest, and storage basket. Height adjustable with ergonomic hand brakes and large wheels for outdoor use.",
        "price": 7499.0,
        "rating": 4.6,
        "stock": 55,
        "features": ["Ergonomic hand brakes", "Padded seat & backrest", "Storage basket", "Height adjustable", "Folding design"],
        "specs": {"weight_capacity": "130kg", "wheel_size": "20cm", "weight": "6.8kg", "frame": "Aluminum"},
        "condition_tags": "elderly mobility, post-surgery, balance disorder, Parkinson's, general weakness",
        "image_url": "https://example.com/images/rollator.jpg",
    },
    {
        "sku": "AM-MA-002",
        "name": "AquaMax Electric Wheelchair",
        "category": "Mobility Aids",
        "subcategory": "Wheelchair",
        "description": "Compact electric wheelchair with joystick control, 25km range, and foldable frame. Suitable for indoor and outdoor use with suspension.",
        "price": 54999.0,
        "rating": 4.7,
        "stock": 10,
        "features": ["Joystick control", "25km range", "Foldable frame", "Suspension system", "Speed: 0-6 km/h"],
        "specs": {"max_speed": "6 km/h", "range": "25km", "weight_capacity": "120kg", "battery": "24V 20Ah", "weight": "28kg"},
        "condition_tags": "paraplegia, spinal cord injury, multiple sclerosis, muscular dystrophy, elderly mobility",
        "image_url": "https://example.com/images/e-wheelchair.jpg",
    },
    {
        "sku": "AM-MA-003",
        "name": "AquaMax Patient Transfer Lift",
        "category": "Mobility Aids",
        "subcategory": "Patient Lift",
        "description": "Electric patient transfer lift for safe moving and handling of patients with limited mobility. 180kg capacity with sling included.",
        "price": 28999.0,
        "rating": 4.8,
        "stock": 7,
        "features": ["Electric lift motor", "180kg capacity", "Sling included", "Emergency lowering", "Adjustable base"],
        "specs": {"capacity": "180kg", "lift_range": "50-180cm", "base_width": "adjustable", "weight": "32kg"},
        "condition_tags": "bedridden, post-surgery, spinal injury, elderly care, neurological disorder",
        "image_url": "https://example.com/images/patient-lift.jpg",
    },
    # Massage & Manual Therapy
    {
        "sku": "AM-MT-001",
        "name": "AquaMax Professional Massage Table",
        "category": "Massage Therapy",
        "subcategory": "Treatment Table",
        "description": "3-section electric massage table with height adjustment, face cradle, and armrests. Premium upholstery with 250kg capacity.",
        "price": 18999.0,
        "rating": 4.7,
        "stock": 14,
        "features": ["Electric height adjustment", "3-section design", "Face cradle & armrests", "Premium upholstery", "250kg capacity"],
        "specs": {"dimensions": "195cm x 70cm", "height_range": "55-95cm", "capacity": "250kg", "weight": "42kg"},
        "condition_tags": "physiotherapy clinic, massage therapy, chiropractic, osteopathy, general treatment",
        "image_url": "https://example.com/images/massage-table.jpg",
    },
    {
        "sku": "AM-MT-002",
        "name": "AquaMax Deep Tissue Massage Gun",
        "category": "Massage Therapy",
        "subcategory": "Percussion Massager",
        "description": "Professional percussion massage gun with 6 attachments and 30 speed levels. Quiet motor with 4-hour battery life for deep tissue therapy.",
        "price": 3999.0,
        "rating": 4.5,
        "stock": 78,
        "features": ["30 speed levels", "6 interchangeable heads", "Quiet brushless motor", "4-hour battery", "LCD display"],
        "specs": {"speeds": 30, "attachments": 6, "battery": "Li-ion 2500mAh", "amplitude": "12mm", "weight": "900g"},
        "condition_tags": "muscle recovery, sports massage, DOMS, myofascial release, general pain relief",
        "image_url": "https://example.com/images/massage-gun.jpg",
    },
    # Diagnostic
    {
        "sku": "AM-DG-001",
        "name": "AquaMax Dynamometer (Hand Grip)",
        "category": "Diagnostic",
        "subcategory": "Strength Testing",
        "description": "Digital hand grip dynamometer for measuring grip strength in rehabilitation and research. Auto-capture with Bluetooth data export.",
        "price": 8499.0,
        "rating": 4.4,
        "stock": 22,
        "features": ["Digital LCD display", "Auto-capture", "Bluetooth data export", "Adjustable handle", "Carrying case"],
        "specs": {"range": "0-90kg", "accuracy": "±0.1kg", "units": "kg, lb, N", "battery": "AAA x 2", "weight": "350g"},
        "condition_tags": "grip strength assessment, stroke rehab, hand injury, research, geriatric assessment",
        "image_url": "https://example.com/images/dynamometer.jpg",
    },
    {
        "sku": "AM-DG-002",
        "name": "AquaMax Goniometer Set (Digital)",
        "category": "Diagnostic",
        "subcategory": "Range of Motion",
        "description": "Set of 3 digital goniometers for precise joint range of motion measurement. LCD display with memory function and ergonomic design.",
        "price": 3499.0,
        "rating": 4.3,
        "stock": 35,
        "features": ["Set of 3 sizes", "Digital LCD", "Memory function", "±0.5° accuracy", "Ergonomic arms"],
        "specs": {"sizes": "15cm, 30cm, 45cm", "accuracy": "±0.5°", "display": "LCD", "battery": "CR2032", "weight": "200g"},
        "condition_tags": "range of motion assessment, joint flexibility, orthopedic evaluation, physiotherapy assessment",
        "image_url": "https://example.com/images/goniometer.jpg",
    },
    # Pediatric Rehab
    {
        "sku": "AM-PD-001",
        "name": "AquaMax Pediatric Standing Frame",
        "category": "Pediatric Rehabilitation",
        "subcategory": "Standing Frame",
        "description": "Adjustable standing frame for children with cerebral palsy and developmental disorders. Supports upright posture with adjustable trays and supports.",
        "price": 24999.0,
        "rating": 4.8,
        "stock": 6,
        "features": ["Height adjustable 80-140cm", "Trays & activity surfaces", "Safety harness", "Wheels with brakes", "Growth adaptable"],
        "specs": {"height_range": "80-140cm", "max_weight": "50kg", "material": "Steel", "weight": "18kg"},
        "condition_tags": "cerebral palsy, developmental delay, pediatric rehab, standing training, hypotonia",
        "image_url": "https://example.com/images/pediatric-stander.jpg",
    },
    {
        "sku": "AM-PD-002",
        "name": "AquaMax Pediatric Therapy Ball Set",
        "category": "Pediatric Rehabilitation",
        "subcategory": "Sensory Integration",
        "description": "Set of 5 anti-burst therapy balls in varying sizes for pediatric sensory integration, balance training, and core strengthening.",
        "price": 2199.0,
        "rating": 4.2,
        "stock": 65,
        "features": ["Anti-burst material", "5 sizes: 30-65cm", "Pump included", "Color-coded", "Non-slip surface"],
        "specs": {"sizes": "30, 40, 50, 55, 65cm", "material": "PVC", "max_weight": "200kg", "weight": "3kg total"},
        "condition_tags": "sensory integration, pediatric therapy, balance training, ADHD, autism, core strengthening",
        "image_url": "https://example.com/images/pediatric-balls.jpg",
    },
    # Home Care
    {
        "sku": "AM-HC-003",
        "name": "AquaMax Adjustable Hospital Bed (Home)",
        "category": "Home Care",
        "subcategory": "Hospital Bed",
        "description": "Electric 5-function hospital bed for home care with side rails, remote control, and Trendelenburg positioning. Medical-grade mattress included.",
        "price": 45999.0,
        "rating": 4.7,
        "stock": 9,
        "features": ["5-function electric", "Remote control", "Side rails", "Trendelenburg position", "Medical mattress included"],
        "specs": {"dimensions": "200cm x 90cm", "height_range": "40-80cm", "max_weight": "180kg", "weight": "95kg"},
        "condition_tags": "home care, bedridden, post-surgery, elderly care, paralysis, long-term care",
        "image_url": "https://example.com/images/hospital-bed.jpg",
    },
    {
        "sku": "AM-HC-004",
        "name": "AquaMax Over-Bed Table",
        "category": "Home Care",
        "subcategory": "Patient Table",
        "description": "Height-adjustable over-bed table with tilt-top surface, wheels, and side cup holder. Ideal for meals, reading, and laptop use in bed.",
        "price": 2499.0,
        "rating": 4.3,
        "stock": 80,
        "features": ["Height adjustable", "Tilt-top surface", "Locking wheels", "Cup holder", "Easy assembly"],
        "specs": {"surface": "60cm x 40cm", "height_range": "70-110cm", "max_weight": "25kg", "weight": "4.5kg"},
        "condition_tags": "bedridden, home care, elderly, post-surgery, convenience",
        "image_url": "https://example.com/images/overbed-table.jpg",
    },
    # Sports Rehab
    {
        "sku": "AM-SR-001",
        "name": "AquaMax Isokinetic Testing System",
        "category": "Sports Rehabilitation",
        "subcategory": "Isokinetic Testing",
        "description": "Clinical-grade isokinetic testing and training system for muscle strength assessment and rehabilitation. Computerized with real-time feedback.",
        "price": 485000.0,
        "rating": 4.9,
        "stock": 2,
        "features": ["Computerized control", "Real-time biofeedback", "Multiple test modes", "Exportable reports", "Safety stops"],
        "specs": {"speed_range": "0-500°/s", "torque_accuracy": "±1%", "software": "Windows-based", "weight": "320kg"},
        "condition_tags": "ACL rehab, sports medicine, muscle strength testing, athletic performance, research",
        "image_url": "https://example.com/images/isokinetic.jpg",
    },
    {
        "sku": "AM-SR-002",
        "name": "AquaMax Plyometric Box Set",
        "category": "Sports Rehabilitation",
        "subcategory": "Plyometrics",
        "description": "Set of 4 stackable plyometric boxes (15, 30, 45, 60cm) for jump training, rehabilitation, and functional fitness. Anti-slip surface.",
        "price": 6499.0,
        "rating": 4.4,
        "stock": 28,
        "features": ["4 stackable heights", "Anti-slip surface", "Rubber feet", "Steel frame", "Max weight 200kg"],
        "specs": {"heights": "15, 30, 45, 60cm", "material": "Steel", "max_weight": "200kg", "weight": "22kg total"},
        "condition_tags": "jump training, ACL rehab, functional fitness, sports conditioning, explosive power",
        "image_url": "https://example.com/images/plyo-box.jpg",
    },
    # Neurological Rehab
    {
        "sku": "AM-NR-001",
        "name": "AquaMax Functional Electrical Stimulation (FES) Bike",
        "category": "Neurological Rehabilitation",
        "subcategory": "FES",
        "description": "FES cycling system for spinal cord injury and neurological rehabilitation. Electrical stimulation activates paralyzed muscles for active cycling.",
        "price": 285000.0,
        "rating": 4.8,
        "stock": 2,
        "features": ["12-channel FES", "Adjustable resistance", "Software control", "Real-time muscle monitoring", "Safety cutoff"],
        "specs": {"channels": 12, "resistance": "0-100W", "software": "Windows-based", "weight": "85kg"},
        "condition_tags": "spinal cord injury, stroke, multiple sclerosis, neurological disorder, muscle activation",
        "image_url": "https://example.com/images/fes-bike.jpg",
    },
    {
        "sku": "AM-NR-002",
        "name": "AquaMax Virtual Reality Rehab System",
        "category": "Neurological Rehabilitation",
        "subcategory": "VR Therapy",
        "description": "Immersive VR rehabilitation system for neurological and motor recovery. Gamified exercises with motion tracking and progress analytics.",
        "price": 125000.0,
        "rating": 4.7,
        "stock": 4,
        "features": ["VR headset included", "Motion tracking", "Gamified exercises", "Progress analytics", "Multi-patient profiles"],
        "specs": {"headset": "Meta Quest 2", "tracking": "6 DOF", "exercises": "50+", "software": "Cloud-based", "weight": "5kg"},
        "condition_tags": "stroke rehab, Parkinson's, brain injury, cognitive rehab, motor control, balance training",
        "image_url": "https://example.com/images/vr-rehab.jpg",
    },
    # Respiratory Rehab
    {
        "sku": "AM-RR-001",
        "name": "AquaMax Spirometer (Digital Incentive)",
        "category": "Respiratory Rehabilitation",
        "subcategory": "Spirometry",
        "description": "Digital incentive spirometer for respiratory rehabilitation and lung capacity training. LCD display with goal-setting and progress tracking.",
        "price": 1899.0,
        "rating": 4.3,
        "stock": 120,
        "features": ["Digital LCD", "Goal-setting", "Progress tracking", "Hygienic disposable mouthpieces", "Compact design"],
        "specs": {"volume_range": "0-5000mL", "accuracy": "±3%", "display": "LCD", "battery": "CR2032", "weight": "120g"},
        "condition_tags": "COPD, post-surgery lung recovery, asthma, pneumonia recovery, respiratory weakness",
        "image_url": "https://example.com/images/spirometer.jpg",
    },
    {
        "sku": "AM-RR-002",
        "name": "AquaMax Oscillating Positive Expiratory Pressure (OPEP) Device",
        "category": "Respiratory Rehabilitation",
        "subcategory": "Airway Clearance",
        "description": "OPEP device for airway clearance in COPD, cystic fibrosis, and post-surgical patients. Adjustable resistance with vibrating mesh technology.",
        "price": 2499.0,
        "rating": 4.5,
        "stock": 90,
        "features": ["Adjustable resistance", "Vibrating mesh", "Hygienic design", "Portable", "Mouthpiece & mask included"],
        "specs": {"resistance_levels": 5, "flow_range": "5-30 L/min", "material": "Medical grade", "weight": "80g"},
        "condition_tags": "COPD, cystic fibrosis, bronchitis, mucus clearance, post-surgical, asthma",
        "image_url": "https://example.com/images/opep-device.jpg",
    },
    # Traction & Decompression
    {
        "sku": "AM-TD-001",
        "name": "AquaMax Cervical Traction Device",
        "category": "Traction Therapy",
        "subcategory": "Cervical Traction",
        "description": "Over-door cervical traction device for neck pain relief and decompression. Adjustable weight with padded head halter and spreader bar.",
        "price": 2999.0,
        "rating": 4.2,
        "stock": 48,
        "features": ["Over-door setup", "Adjustable weight 1-10kg", "Padded head halter", "Spreader bar", "Easy assembly"],
        "specs": {"weight_range": "1-10kg", "halter_material": "Cotton", "door_clip": "Metal", "weight": "800g"},
        "condition_tags": "cervical spondylosis, neck pain, herniated disc, radiculopathy, tension headache",
        "image_url": "https://example.com/images/cervical-traction.jpg",
    },
    {
        "sku": "AM-TD-002",
        "name": "AquaMax Lumbar Traction Table",
        "category": "Traction Therapy",
        "subcategory": "Lumbar Traction",
        "description": "Electric lumbar traction table with computerized decompression, heat therapy, and adjustable patient positioning. Clinical-grade for clinics.",
        "price": 125000.0,
        "rating": 4.8,
        "stock": 4,
        "features": ["Computerized decompression", "Heat therapy integrated", "Adjustable positioning", "Safety sensors", "Treatment presets"],
        "specs": {"traction_force": "0-90kg", "table_length": "200cm", "heat": "40-50°C", "weight": "180kg"},
        "condition_tags": "lumbar disc herniation, sciatica, spinal stenosis, chronic back pain, degenerative disc disease",
        "image_url": "https://example.com/images/lumbar-traction.jpg",
    },
    # Compression Therapy
    {
        "sku": "AM-CP-001",
        "name": "AquaMax Intermittent Pneumatic Compression (IPC) System",
        "category": "Compression Therapy",
        "subcategory": "IPC",
        "description": "Clinical IPC system for lymphedema, DVT prevention, and circulation improvement. 4-chamber sequential compression with adjustable pressure and timer.",
        "price": 18999.0,
        "rating": 4.6,
        "stock": 16,
        "features": ["4-chamber sequential", "Adjustable pressure 30-120mmHg", "Timer", "Leg & arm garments included", "Quiet pump"],
        "specs": {"chambers": 4, "pressure_range": "30-120mmHg", "garments": "leg, arm", "weight": "3.5kg"},
        "condition_tags": "lymphedema, DVT prevention, circulation issues, post-surgical swelling, chronic venous insufficiency",
        "image_url": "https://example.com/images/ipc-system.jpg",
    },
    {
        "sku": "AM-CP-002",
        "name": "AquaMax Compression Pump (Home)",
        "category": "Compression Therapy",
        "subcategory": "Home Compression",
        "description": "Compact home compression pump for daily use. Single-leg garment with 3 compression modes and adjustable pressure for lymphedema management.",
        "price": 6499.0,
        "rating": 4.3,
        "stock": 38,
        "features": ["3 compression modes", "Adjustable pressure", "Single-leg garment", "Quiet operation", "Auto shut-off"],
        "specs": {"modes": 3, "pressure_range": "20-80mmHg", "garment": "single leg", "timer": "1-60 min", "weight": "1.8kg"},
        "condition_tags": "lymphedema, leg swelling, varicose veins, post-surgery recovery, elderly circulation",
        "image_url": "https://example.com/images/compression-home.jpg",
    },
    # Laser Therapy
    {
        "sku": "AM-LT-001",
        "name": "AquaMax Low-Level Laser Therapy (LLLT) Device",
        "category": "Laser Therapy",
        "subcategory": "LLLT",
        "description": "Clinical LLLT device with 650nm and 808nm wavelengths for pain relief, tissue healing, and inflammation reduction. Handheld with treatment timer.",
        "price": 24999.0,
        "rating": 4.5,
        "stock": 13,
        "features": ["Dual wavelength 650nm & 808nm", "Adjustable power", "Treatment timer", "Portable", "Safety goggles included"],
        "specs": {"wavelengths": "650nm, 808nm", "power": "100-500mW", "timer": "1-30 min", "battery": "Li-ion", "weight": "450g"},
        "condition_tags": "chronic pain, wound healing, tendonitis, inflammation, arthritis, soft tissue injury",
        "image_url": "https://example.com/images/lllt-device.jpg",
    },
    # Shockwave Therapy
    {
        "sku": "AM-SW-001",
        "name": "AquaMax Extracorporeal Shockwave Therapy (ESWT) Unit",
        "category": "Shockwave Therapy",
        "subcategory": "ESWT",
        "description": "Radial shockwave therapy unit for chronic musculoskeletal conditions, plantar fasciitis, and tendon disorders. 5 applicators with adjustable intensity.",
        "price": 185000.0,
        "rating": 4.8,
        "stock": 3,
        "features": ["Radial shockwave", "5 applicators", "Adjustable intensity 1-5 bar", "Touchscreen control", "Treatment counter"],
        "specs": {"frequency": "1-22 Hz", "pressure": "1-5 bar", "applicators": 5, "power": "AC 220V", "weight": "8kg"},
        "condition_tags": "plantar fasciitis, tennis elbow, calcific tendinitis, chronic tendinopathy, cellulite, erectile dysfunction",
        "image_url": "https://example.com/images/shockwave.jpg",
    },
    # Continuous Passive Motion (CPM)
    {
        "sku": "AM-CPM-001",
        "name": "AquaMax Knee CPM Machine",
        "category": "CPM Therapy",
        "subcategory": "Knee CPM",
        "description": "Knee continuous passive motion machine for post-surgical knee rehabilitation. Adjustable speed, range, and pause time with patient safety features.",
        "price": 54999.0,
        "rating": 4.7,
        "stock": 8,
        "features": ["Adjustable range 0-120°", "Speed control", "Pause timer", "Remote control", "Safety sensors"],
        "specs": {"range": "0-120°", "speed": "1-8°/s", "pause": "0-30s", "max_weight": "150kg", "weight": "22kg"},
        "condition_tags": "knee replacement, ACL reconstruction, post-surgical knee, joint stiffness, arthroscopy",
        "image_url": "https://example.com/images/knee-cpm.jpg",
    },
    # Wheelchair Accessories
    {
        "sku": "AM-WA-001",
        "name": "AquaMax Pressure Relief Cushion (Gel)",
        "category": "Wheelchair Accessories",
        "subcategory": "Cushion",
        "description": "Gel-infused pressure relief cushion for wheelchair users. Reduces pressure sores, improves comfort, and promotes airflow with breathable cover.",
        "price": 2499.0,
        "rating": 4.4,
        "stock": 110,
        "features": ["Gel-infused core", "Breathable cover", "Waterproof base", "Non-slip bottom", "Machine washable cover"],
        "specs": {"dimensions": "45cm x 45cm x 5cm", "material": "Gel + foam", "max_weight": "150kg", "weight": "1.5kg"},
        "condition_tags": "pressure sore prevention, wheelchair user, spinal injury, elderly, long-term sitting",
        "image_url": "https://example.com/images/gel-cushion.jpg",
    },
    # General
    {
        "sku": "AM-GN-001",
        "name": "AquaMax Therapy Hot Pack (Microwaveable)",
        "category": "General Therapy",
        "subcategory": "Heat Pack",
        "description": "Reusable microwaveable hot pack for moist heat therapy. Flexible gel construction conforms to body contours for targeted pain relief.",
        "price": 899.0,
        "rating": 4.2,
        "stock": 200,
        "features": ["Microwaveable", "Reusable", "Flexible gel", "Moist heat", "Machine washable cover"],
        "specs": {"dimensions": "30cm x 20cm", "material": "Gel", "heat_time": "2-3 min", "weight": "800g"},
        "condition_tags": "muscle pain, menstrual cramps, back pain, arthritis, general pain relief",
        "image_url": "https://example.com/images/hot-pack.jpg",
    },
    {
        "sku": "AM-GN-002",
        "name": "AquaMax Therapy Cold Pack (Reusable)",
        "category": "General Therapy",
        "subcategory": "Cold Pack",
        "description": "Reusable cold pack with instant cold technology for acute injury management, swelling reduction, and pain relief. Flexible when frozen.",
        "price": 699.0,
        "rating": 4.1,
        "stock": 250,
        "features": ["Instant cold technology", "Flexible when frozen", "Reusable", "Leak-proof", "Velcro strap"],
        "specs": {"dimensions": "25cm x 15cm", "material": "Gel", "cold_duration": "30-45 min", "weight": "500g"},
        "condition_tags": "acute injury, swelling, sports injury, bruising, post-surgical, inflammation",
        "image_url": "https://example.com/images/cold-pack.jpg",
    },
]


def seed_products() -> None:
    """Insert seed products into the database."""
    setup_logging(settings)
    logger = get_logger(__name__)
    
    init_database()
    
    with get_session() as session:
        # Check if already seeded
        from src.database.repository import ProductRepository
        repo = ProductRepository(session)
        if repo.count() > 0:
            logger.info("Database already seeded with %d products. Skipping.", repo.count())
            return
        
        for data in SEED_PRODUCTS:
            product = Product(
                sku=data["sku"],
                name=data["name"],
                category=data["category"],
                subcategory=data["subcategory"],
                description=data["description"],
                price=data["price"],
                rating=data["rating"],
                stock=data["stock"],
                features=json.dumps(data["features"]),
                specs=json.dumps(data["specs"]),
                condition_tags=data["condition_tags"],
                image_url=data["image_url"],
            )
            repo.create(product)
        
        logger.info("Seeded %d products into the AquaMax database.", len(SEED_PRODUCTS))


if __name__ == "__main__":
    seed_products()
